# Generated by Django 2.1.1 on 2018-12-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=8, null=True)),
                ('institute', models.CharField(choices=[('信息与通信工程学院', '信息与通信工程学院'), ('电子工程学院', '电子工程学院'), ('计算机学院', '计算机学院'), ('自动化学院', '自动化学院'), ('数字媒体与设计艺术学院', '数字媒体与设计艺术学院'), ('现代邮政学院', '现代邮政学院'), ('网络空间安全学院', '网络空间安全学院'), ('光电信息学院', '光电信息学院'), ('理学院', '理学院'), ('经济管理学院', '经济管理学院'), ('公共管理学院', '公共管理学院'), ('人文学院', '人文学院'), ('国际学院', '国际学院'), ('软件学院', '软件学院')], max_length=15, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=10, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('email', models.EmailField(default='example@example.com', max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Team'),
        ),
    ]
