# Generated by Django 2.1.1 on 2018-10-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181017_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mateA',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mateB',
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=30, unique=True),
        ),
    ]
