# Generated by Django 2.1.1 on 2018-12-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompeteMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, unique=True)),
                ('detail', models.CharField(default='', max_length=300)),
                ('datetime_begin', models.DateTimeField(null=True)),
                ('datetime_end', models.DateTimeField(null=True)),
                ('creator', models.CharField(default='root', max_length=25)),
                ('isTeam', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, unique=True)),
                ('link', models.CharField(default='', max_length=100, null=True)),
                ('detail', models.CharField(default='', max_length=300, null=True)),
                ('author', models.CharField(default='root', max_length=25, null=True)),
                ('bill', models.IntegerField(default=0)),
                ('solvedCount', models.IntegerField(default=0, null=True)),
                ('type', models.IntegerField(default=0)),
                ('flag', models.CharField(default='', max_length=80, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='problemFile/%Y-%m-%d')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_done', models.DateTimeField(null=True)),
                ('res', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Contest')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Problem')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Person')),
            ],
        ),
        migrations.AddField(
            model_name='competemsg',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Contest'),
        ),
        migrations.AddField(
            model_name='competemsg',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Person'),
        ),
        migrations.AddField(
            model_name='competemsg',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Team'),
        ),
    ]
