# Generated by Django 2.1.1 on 2018-10-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, unique=True)),
                ('detail', models.CharField(default='', max_length=300)),
                ('datetime_begin', models.DateTimeField(null=True)),
                ('datetime_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, unique=True)),
                ('detail', models.CharField(default='', max_length=300)),
                ('author', models.CharField(default='unknown', max_length=25)),
                ('bill', models.IntegerField(default=0)),
                ('solvedCount', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('flag', models.CharField(default='', max_length=80, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='./problemsFile/')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Contests')),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_done', models.DateTimeField(null=True)),
                ('res', models.IntegerField(default=0)),
                ('problem_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
            ],
        ),
    ]
