# Generated by Django 2.1.1 on 2018-10-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20181011_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='creater',
            field=models.CharField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='solved',
            name='problem_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solved',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
