# Generated by Django 2.1.1 on 2018-10-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20181011_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./problemFile/'),
        ),
    ]
