# Generated by Django 2.1.1 on 2018-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20181013_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='creater',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='problemFile/%Y-%m-%d'),
        ),
    ]
