# Generated by Django 2.1.1 on 2018-10-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20181014_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='contest_id',
            field=models.IntegerField(default=0),
        ),
    ]
