# Generated by Django 2.1.1 on 2018-10-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_solved_contest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solved',
            name='res',
            field=models.BooleanField(default=False),
        ),
    ]
