# Generated by Django 2.1.1 on 2018-10-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20181016_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='isTeam',
            field=models.BooleanField(default=False),
        ),
    ]
