# Generated by Django 2.1.1 on 2018-10-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_team'),
        ('challenges', '0009_contest_isteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solved',
            name='contest_id',
        ),
        migrations.RemoveField(
            model_name='solved',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='solved',
            name='user_id',
        ),
        migrations.AddField(
            model_name='solved',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Contest'),
        ),
        migrations.AddField(
            model_name='solved',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Problem'),
        ),
        migrations.AddField(
            model_name='solved',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Team'),
        ),
        migrations.AddField(
            model_name='solved',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Person'),
        ),
    ]
