# Generated by Django 2.1.1 on 2018-10-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181017_1116'),
        ('challenges', '0011_auto_20181017_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompeteMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Contest')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Person')),
            ],
        ),
    ]
