# Generated by Django 2.1.1 on 2018-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_competemsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='competemsg',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
