# Generated by Django 2.1.1 on 2018-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_competemsg_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
