# Generated by Django 2.1.1 on 2018-11-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_problem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.CharField(default='root', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detail',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solvedCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
