# Generated by Django 2.1.1 on 2018-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_auto_20181124_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='link',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
